GET http://localhost:8080/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json


{
    "name": "Kathi W Ward",
    "type": "Property",
    "holder_first_name": "Kathi",
    "holder_last_name": "Ward",
    "holder_account_id": "H77774SW543",
    "is_active": true,
    "has_active_claim": false,
    "effective_date": "2020-01-01",
    "termination_date": "2021-12-31"
}

###

GET http://localhost:8080/api/policies/5f98804a57d23a4a189a03f9 HTTP/1.1
Content-Type:application/json

###
//update by ID 
PUT http://localhost:8080/api/policies/5f98804a57d23a4a189a03f9 HTTP/1.1
Content-Type: application/json

{
    "name": "Sunny Regan"
}

###
//delete byID
DELETE  http://localhost:8080/api/policies/5f98804a57d23a4a189a03f9 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json
