GET http://localhost:8080/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/api/policies HTTP/1.1
Content-Type: application/json


{
    "name": "Kathi Ward",
    "type": "Property",
    "holder_first_name": "Kathi",
    "holder_last_name": "Ward",
    "holder_account_id": "H77774SW543",
    "is_active": true,
    "has_active_claim": false,
    "effective_date": "2020-01-01",
    "termination_date": "2021-12-31"
}